# Generated by Django 4.0.5 on 2022-06-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('title', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=92, null=True)),
                ('isbn', models.CharField(db_collation='utf8_general_ci', db_column='ISBN', max_length=17, primary_key=True, serialize=False)),
                ('author', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=56, null=True)),
                ('description', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=3558, null=True)),
            ],
            options={
                'db_table': 'books',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
